# Generated by Django 3.1.7 on 2021-05-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(max_length=500)),
                ('año', models.IntegerField(max_length=100)),
                ('generos', models.ManyToManyField(blank=True, null=True, to='home.Genero')),
            ],
        ),
    ]
