# Generated by Django 3.1.7 on 2021-05-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='generos',
            new_name='genero',
        ),
    ]
