# Generated by Django 3.1.7 on 2021-05-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210505_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.ManyToManyField(to='home.Genero'),
        ),
    ]
