# Generated by Django 3.1.7 on 2021-05-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210505_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='año',
            field=models.IntegerField(),
        ),
    ]
